### ISSUE TITLE
Upgraded to node 8 and the build is not working anymore

### ISSUE THREAD

**Issue by rihabesx** [nukedzn/node-tcl#12]
Hi,

On my linux machine, I had the library working in my project, but then I upgraded from node 7 to node v 8.1.3 and npm 5.2.0 and upon the next npm install I started getting the following node_module_version incompatibility error like this:

I tried running npm run install inside the tcl directory in node_modules but still get the same error.

I appreciate your response in order to make work on node 8

dist/node_modules/tcl/build/Release/tcl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/dist/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/dist/node_modules/tcl/lib/tcl.js:4:36)

**Comment by uditha-atukorala** [comment]
I didn't check this myself but usually native plugins don't get compiled after the first install (unless there's a package version upgrade). So if you install the _tcl_ package while using Node.js v7 and then later upgrade to Node.js v8, it won't do a new compile against Node.js v8 with a `npm install`. 

You could try `npm rebuild` or just remove the `node_modules` directory and do a `npm install` again. Or you can remove `node_modules/tcl` and do a `npm install` if you don't want to reinstall all the other packages.
