### ISSUE TITLE
Can't compile against node 10+

### ISSUE THREAD

**Issue by rihabesx** [nukedzn/node-tcl#13]
Kindly advise how to fix this issue

Error: The module '/node_modules/tcl/build/Release/tcl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Tried running npm rebuild and reinstall but still the same error.

I appreciate if you could answer me.

**Comment by Azerothian** [comment]
```
error projects/external/tcltest/node_modules/tcl: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: projects/external/tcltest/node_modules/tcl
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   'projects/external/tcltest/node_modules/tcl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '.cache/node-gyp/14.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=.cache/node-gyp/14.15.0',
gyp info spawn args   '-Dnode_gyp_dir=.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=.cache/node-gyp/14.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=projects/external/tcltest/node_modules/tcl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory 'projects/external/tcltest/node_modules/tcl/build'
  CXX(target) Release/obj.target/tcl/src/tclbinding.o
In file included from ../../nan/nan.h:56,
                 from ../src/tclbinding.h:5,
                 from ../src/tclbinding.cpp:2:
.cache/node-gyp/14.15.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
.cache/node-gyp/14.15.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/tclbinding.h:39:1: note: in expansion of macro ‘NODE_MODULE’
   39 | NODE_MODULE( tcl, TclBinding::init )
      | ^~~~~~~~~~~
../src/tclbinding.cpp: In static member function ‘static void TclBinding::init(v8::Local<v8::Object>)’:
../src/tclbinding.cpp:61:38: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   61 |  constructor.Reset( tpl->GetFunction() );
      |                                      ^
In file included from .cache/node-gyp/14.15.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/tclbinding.h:5,
                 from ../src/tclbinding.cpp:2:
.cache/node-gyp/14.15.0/include/node/v8.h:6475:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6475 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
.cache/node-gyp/14.15.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
../src/tclbinding.cpp:62:76: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   62 |  exports->Set( Nan::New( "TclBinding" ).ToLocalChecked(), tpl->GetFunction() );
      |                                                                            ^
In file included from .cache/node-gyp/14.15.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/tclbinding.h:5,
                 from ../src/tclbinding.cpp:2:
.cache/node-gyp/14.15.0/include/node/v8.h:6475:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6475 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
.cache/node-gyp/14.15.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
../src/tclbinding.cpp: In static member function ‘static void TclBinding::toArray(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/tclbinding.cpp:222:89: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::String>)’
  222 |    r_array->Set( i, Nan::New< v8::String >( Tcl_GetString( objv[i] ) ).ToLocalChecked() );
      |                                                                                         ^
In file included from .cache/node-gyp/14.15.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/tclbinding.h:5,
                 from ../src/tclbinding.cpp:2:
.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
make: *** [tcl.target.mk:122: Release/obj.target/tcl/src/tclbinding.o] Error 1
make: Leaving directory 'projects/external/tcltest/node_modules/tcl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-53-generic
gyp ERR! command ".nvm/versions/node/v14.15.0/bin/node" ".nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd projects/external/tcltest/node_modules/tcl
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by uditha-atukorala** [comment]
@gotchoices kindly submitted #14 should get it working for Node.js v16 (LTS).
